import Head from 'next/head'

const About = () => {
  return (
    <div>
      <Head>
        <title>ABOUT ME</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>about me</div>
    </div>
  )
}

export default About